### ISSUE TITLE
Test on PHP 8.1 and 8.2

### ISSUE THREAD

**Issue by reedy** [wikimedia/php-cssjanus#39]
After https://github.com/wikimedia/php-cssjanus/issues/37

**Comment by reedy** [comment]
8.2 testing passing on phan blocked due to https://github.com/wikimedia/phan-taint-check-plugin/commit/fc31270ae44a72ad2eb482fab4a3f7be1135053d being unreleased

**Comment by Krinkle** [comment]
Will be done in WMF CI when the repo is on Gerrit (mirrored at <https://github.com/wikimedia/mediawiki-libs-php-cssjanus>). Closing now so that the issue count won't be stuck at 1 when this GitHub repo gets archived.
